### ISSUE TITLE
未看到如何转为onnx格式

### ISSUE THREAD

**Issue by LongKaiAAA** [SWHL/ConvertLOREToONNX#1]
在main.py中，没看到转为onnx的代码

**Comment by SWHL** [comment]
不在main中，可以下载下来，全局搜索一下torch.onnx.expirt

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月21日 13:38 |
| 收件人 | SWHL/ConvertLOREToONNX ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [SWHL/ConvertLOREToONNX] 未看到如何转为onnx格式 (Issue #1) |

在main.py中，没看到转为onnx的代码

**Comment by SWHL** [comment]
不在main中，可以下载下来，全局搜索一下torch.onnx.export

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月21日 13:38 |
| 收件人 | SWHL/ConvertLOREToONNX ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [SWHL/ConvertLOREToONNX] 未看到如何转为onnx格式 (Issue #1) |

在main.py中，没看到转为onnx的代码
